name: Build Enmity and Inject Rosiecord with k2genmity
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity and Inject Rosiecord with k2genmity
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main utils are installed are installed
        id: core
        run: brew install coreutils ldid
        
      - name: Run Main Node Script to Patch Rosiecord (With k2genmity as a argv)
        id: node_sh
        run: node ./index.js k2genmity
        
      - name: Retrieve version
        run: |
          cd ./ipas
          echo "::set-output name=DISCORD_VERSION::$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)"   
        id: version
        
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: rosiecord_${{ steps.version.outputs.DISCORD_VERSION }}_k2genmity
          title: Rosiecord ${{ steps.version.outputs.DISCORD_VERSION }} (K2Genmity)
          files: Dist_K2genmity/*.ipa