name: Build Enmity and Inject Rosiecord
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main utils are installed
        id: core
        run: brew install coreutils ldid

      - name: Run Main Node Script to Patch Rosiecord
        id: build
        run: node ./index.js
        
      - name: Retrieve version
        id: version
        run: |
          cd ./ipas
          echo "__DISCORD_VERSION=$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)" >> $GITHUB_OUTPUT  

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: rosiecord_${{ steps.version.outputs.__DISCORD_VERSION }}
          title: Rosiecord ${{ steps.version.outputs.__DISCORD_VERSION }}
          files: Dist/*.ipa